---
  - name: "test reachability & check details of files in directory"
    hosts: localhost

    tasks:

      - name: "test reachability"
        ping:

      - name: "check details"
        find:
          file_type: file
          patterns: "*.txt"
          paths: "~/Developer/cloud-devops-engineer-training/Ansible/challenge"