pipeline {
    agent { label 'linux' }
    tools {
        maven 'Maven-3.8.4'
    }
    stages {
        stage('Source') {
            steps {
                git branch: 'main',
                    changelog: false,
                    poll: false,
                    url: 'https://github.com/maciejkalis/cloud-devops-engineer-training.git'
            }
        }
        stage('Clean') {
            steps {
                dir("${env.WORKSPACE}/Jenkins/Training/Ch5/create-artifacts-and-reports"){
                    echo "Cleaning the workspace..."
                    sh 'mvn clean'
                }
            }
        }
        stage('Test') {
            steps {
                dir("${env.WORKSPACE}/Jenkins/Training/Ch5/create-artifacts-and-reports"){
                    echo "Running tests..."
                    // Uncomment the following line after Maven is configured as a global tool
                    sh 'mvn test'
                }
            }
        }
        stage('Package') {
            steps {
                dir("${env.WORKSPACE}/Jenkins/Training/Ch5/create-artifacts-and-reports"){
                    echo "Creating the JAR file..."
                    // Uncomment the following line after Maven is configured as a global tool
                    sh 'mvn package -DskipTests'
                }
            }
        }
    }
    post {
        always {
            echo "Collecting jUnit test results..."
            junit allowEmptyResults: true,
                testResults: '**/TEST-com.learningjenkins.AppTest.xml'

            echo "Archiving the JAR file..."
            archiveArtifacts allowEmptyArchive: true,
                artifacts: '**/hello-1.0-SNAPSHOT.jar',
                fingerprint: true,
                followSymlinks: false,
                onlyIfSuccessful: true
        }
    }
}
