---
# tasks file for testrole1
- name: Test variable
  debug:
    var: myvar

- name: Start httpd
  service:
    name: apache2
    state: started

- name: Create index.html using Jinja2
  template:
    src: jinja2.j2
    dest: /var/www/html/index.html
